Repository owncloud/docs-client-desktop, pull requests merged in 2021-12, with the labels that each got.

#155 Add AppImage section to supported platforms
  modules/ROOT/pages/installing.adoc
Labels: documentation

#156 [2.9] [PR 155] Add AppImage section to supported platforms
  modules/ROOT/pages/installing.adoc
Labels: backport

#158 update new branch doc
  docs/new-version-branch.md
Labels: deployment

#159 [2.10] [PR 158] update new branch doc
  docs/new-version-branch.md
Labels: backport

#160 [2.9] [PR 158] update new branch doc
  docs/new-version-branch.md
Labels: backport

#161 [2.8] [PR 158] update new branch doc
  docs/new-version-branch.md
Labels: backport
