Repository owncloud/docs-client-desktop, pull requests merged in 2021-11, with the labels that each got.

#132 Adding select capabilities in activities tabs
  modules/ROOT/pages/navigating.adoc
Labels: documentation

#133 [2.9] [PR 132] Adding select capabilities in activities tabs
  modules/ROOT/pages/navigating.adoc
Labels: backport

#137 [2.9] [PR 135] The LICENSE file was a leftover from the code repo - deleting
  LICENSE
Labels: backport

#134 Prepare the repo to include external adoc files
  bin/makepdf
  lib/extensions/remote-include-processor.js
  site.yml
Labels: deployment

#139 [2.8] [PR 134] Prepare the repo to include external adoc files
  bin/makepdf
  lib/extensions/remote-include-processor.js
  site.yml
Labels: backport

#140 [2.9] [PR 134] Prepare the repo to include external adoc files
  bin/makepdf
  lib/extensions/remote-include-processor.js
  site.yml
Labels: backport

#141 Part one fixing broken anchors (in- and inter-document references)
  modules/ROOT/pages/appendices/architecture.adoc
  modules/ROOT/pages/navigating.adoc
Labels: bug

#142 [2.9] [PR 141] Part one fixing broken anchors (in- and inter-document references)
  modules/ROOT/pages/appendices/architecture.adoc
  modules/ROOT/pages/navigating.adoc
Labels: backport

#143 [2.8] [PR 141] Part one fixing broken anchors (in- and inter-document references)
  modules/ROOT/pages/appendices/architecture.adoc
  modules/ROOT/pages/navigating.adoc
Labels: backport

#144 Part three fixing broken anchors (in- and inter-document references)
  modules/ROOT/pages/appendices/architecture.adoc
Labels: bug

#145 [2.9] [PR 144] Part three fixing broken anchors (in- and inter-document references)
  modules/ROOT/pages/appendices/architecture.adoc
Labels: backport

#146 [2.8] [PR 144] Part three fixing broken anchors (in- and inter-document references)
  modules/ROOT/pages/appendices/architecture.adoc
Labels: backport

#147 Fix external broken links
  modules/ROOT/pages/appendices/building.adoc
  modules/ROOT/pages/installing.adoc
Labels: bug

#149 [2.8] [PR 147] Fix external broken links
  modules/ROOT/pages/appendices/building.adoc
  modules/ROOT/pages/installing.adoc
Labels: backport

#150 new faq item on quota
  modules/ROOT/pages/faq.adoc
Labels: documentation

#151 [2.9] [PR 150] new faq item on quota
  modules/ROOT/pages/faq.adoc
Labels: backport

#152 [2.8] [PR 150] new faq item on quota
  modules/ROOT/pages/faq.adoc
Labels: backport
