Repository owncloud/docs-client-desktop, pull requests merged in 2021-09, with the labels that each got.

#94 [2.8] [PR 92] Alternate method for moving the sync folder
  modules/ROOT/pages/faq.adoc
Labels: backport

#93 [2.7] [PR 92] Alternate method for moving the sync folder
  modules/ROOT/pages/faq.adoc
Labels: backport

#101 [2.8] [PR 100] Page alias for build instructions
  modules/ROOT/pages/appendices/building.adoc
Labels: backport

#103 Changes necessary for the 2.9 branch
  .drone.star
  site.yml
Labels: deployment

#105 [2.9] [PR 104] Add note for password on BACKEND_HOST
  modules/ROOT/pages/appendices/guitest.adoc
Labels: backport

#107 [2.9] [PR 106] add more page aliases for pages now in appendices folder
  modules/ROOT/pages/appendices/architecture.adoc
  modules/ROOT/pages/appendices/troubleshooting.adoc
Labels: backport

#108 [2.8] [PR 106] add more page aliases for pages now in appendices folder
  modules/ROOT/pages/appendices/architecture.adoc
  modules/ROOT/pages/appendices/troubleshooting.adoc
Labels: backport

#109 Fix pdf image size
  modules/ROOT/pages/appendices/building.adoc
  modules/ROOT/pages/appendices/troubleshooting.adoc
  modules/ROOT/pages/faq.adoc
  modules/ROOT/pages/installing.adoc
  modules/ROOT/pages/navigating.adoc
  modules/ROOT/pages/vfs.adoc
Labels: bug

#110 [2.8] [PR 109] Fix pdf image size
  modules/ROOT/pages/appendices/building.adoc
  modules/ROOT/pages/appendices/troubleshooting.adoc
  modules/ROOT/pages/faq.adoc
  modules/ROOT/pages/installing.adoc
  modules/ROOT/pages/navigating.adoc
  modules/ROOT/pages/vfs.adoc
Labels: backport

#111 [2.9] [PR 109] Fix pdf image size
  modules/ROOT/pages/appendices/building.adoc
  modules/ROOT/pages/appendices/troubleshooting.adoc
  modules/ROOT/pages/faq.adoc
  modules/ROOT/pages/installing.adoc
  modules/ROOT/pages/navigating.adoc
  modules/ROOT/pages/vfs.adoc
Labels: backport

#113 Update of the makepdf script and configuration to be inline with the other repos
  bin/makepdf
  bin/manual_config
Labels: deployment

#115 [2.9] [PR 113] Update of the makepdf script and configuration to be inline with the other repos
  bin/makepdf
  bin/manual_config
Labels: backport

#116 [2.8] [PR 113] Update of the makepdf script and configuration to be inline with the other repos
  bin/makepdf
  bin/manual_config
Labels: backport

#121 [2.9] [PR 120] Using release notes
  modules/ROOT/nav.adoc
  modules/ROOT/pages/appendices/release_notes.adoc
Labels: backport

#122 [2.8] [PR 120] Using release notes
  modules/ROOT/nav.adoc
  modules/ROOT/pages/appendices/release_notes.adoc
Labels: backport
