Repository owncloud/docs-client-desktop, pull requests merged in 2022-02, with the labels that each got.

#207 Harmonize site.yml to be inline with docs
  site.yml
Labels: deployment

#208 [2.10] [PR 207] Harmonize site.yml to be inline with docs
  site.yml
Labels: backport

#209 [2.9] [PR 207] Harmonize site.yml to be inline with docs
  site.yml
Labels: backport

#210 Add start_page in site.yml
  site.yml
Labels: deployment

#211 [2.10] [PR 210] Add start_page in site.yml
  site.yml
Labels: backport

#212 [2.9] [PR 210] Add start_page in site.yml
  site.yml
Labels: backport

#218 Remove "Availability" from VFS Managed by ownCloud
  modules/ROOT/images/vfs/vfs-disable-virtual-file-support-1.png
  modules/ROOT/images/vfs/vfs-free-up-local-space-done.png
  modules/ROOT/images/vfs/vfs-free-up-local-space-icon.png
  modules/ROOT/images/vfs/vfs-free-up-local-space.png
  modules/ROOT/images/vfs/vfs-make-always-availabe-start-sync.png
  modules/ROOT/images/vfs/vfs-make-always-availabe.png
  modules/ROOT/pages/vfs.adoc
Labels: documentation

#219 [2.10] [PR 218] Remove "Availability" from VFS Managed by ownCloud
  modules/ROOT/images/vfs/vfs-disable-virtual-file-support-1.png
  modules/ROOT/images/vfs/vfs-free-up-local-space-done.png
  modules/ROOT/images/vfs/vfs-free-up-local-space-icon.png
  modules/ROOT/images/vfs/vfs-free-up-local-space.png
  modules/ROOT/images/vfs/vfs-make-always-availabe-start-sync.png
  modules/ROOT/images/vfs/vfs-make-always-availabe.png
  modules/ROOT/pages/vfs.adoc
Labels: backport
