Repository owncloud/docs-client-desktop, pull requests merged in 2022-12, with the labels that each got.

#294 Update the installation description with regards to config files
  modules/ROOT/pages/installing.adoc
Labels: documentation

#295 [2.11] [PR 294] Update the installation description with regards to config files
  modules/ROOT/pages/installing.adoc
Labels: backport

#296 [3.0] [PR 294] Update the installation description with regards to config files
  modules/ROOT/pages/installing.adoc
Labels: backport

#297 Add yarn-bundle command
  package.json
Labels: deployment

#299 [master] [PR 298] Remove macOS legacy builds
  modules/ROOT/pages/installing.adoc
Labels: backport

#300 [2.11] [PR 298] Remove macOS legacy builds
  modules/ROOT/pages/installing.adoc
Labels: backport

#304 [3.0] [PR 302] Adding info about client restart after ignored list changes
  modules/ROOT/pages/navigating.adoc
Labels: backport

#305 [2.11] [PR 302] Adding info about client restart after ignored list changes
  modules/ROOT/pages/navigating.adoc
Labels: backport

#307 Fix a broken internal link
  modules/ROOT/pages/appendices/building.adoc
Labels: documentation

#309 [3.0] [PR 307] Fix a broken internal link
  modules/ROOT/pages/appendices/building.adoc
Labels: backport

#308 [2.11] [PR 307] Fix a broken internal link
  modules/ROOT/pages/appendices/building.adoc
Labels: backport

#310 Add fixes to the appimage description
  modules/ROOT/pages/installing.adoc
Labels: documentation

#311 [3.0] [PR 310] Add fixes to the appimage description
  modules/ROOT/pages/installing.adoc
Labels: backport

#303 Install File Browser Extension Packages
  modules/ROOT/pages/installing.adoc
Labels: documentation

#312 [3.0] [PR 303] Install File Browser Extension Packages
  modules/ROOT/pages/installing.adoc
Labels: backport

#313 [2.11] [PR 303] Install File Browser Extension Packages
  modules/ROOT/pages/installing.adoc
Labels: backport
