Repository owncloud/docs-client-desktop, pull requests merged in 2022-11, with the labels that each got.

#285 [2.11] [PR 280] Update GUI testing docs
  modules/ROOT/pages/appendices/guitest.adoc
Labels: backport

#284 [2.10] [PR 278] Add MSI logging command
  modules/ROOT/pages/installing.adoc
Labels: backport

#283 [2.11] [PR 278] Add MSI logging command
  modules/ROOT/pages/installing.adoc
Labels: backport

#289 Explanation for different file size displays added to FAQ
  modules/ROOT/pages/faq.adoc
Labels: documentation

#292 Changes necessary for 3.0
  .drone.star
  site.yml
Labels: deployment
