Repository owncloud/docs-client-desktop, pull requests merged in 2023-01, with the labels that each got.

#315 Fix owncloudcmd
  modules/ROOT/pages/advanced_usage/command_line_client.adoc
  modules/ROOT/pages/advanced_usage/command_line_options.adoc
  modules/ROOT/partials/nav.adoc
Labels: documentation

#331 [3.0] [PR 329] update testing doc for oCIS
  modules/ROOT/pages/appendices/guitest.adoc
Labels: backport

#332 Fixe the command line page
  modules/ROOT/pages/advanced_usage/command_line_client.adoc
  modules/ROOT/partials/nav.adoc
Labels: documentation

#334 [3.0] [PR 332] Fixe the command line page
  modules/ROOT/pages/advanced_usage/command_line_client.adoc
  modules/ROOT/partials/nav.adoc
Labels: backport

#333 Followup fix for guitest
  modules/ROOT/pages/appendices/guitest.adoc
Labels: documentation

#335 Open files in online office suite
  modules/ROOT/images/web_app/office_file_context_menu.png
  modules/ROOT/images/web_app/office_file_in_browser.png
  modules/ROOT/images/web_app/office_file_in_explorer.png
  modules/ROOT/images/web_app/office_file_in_web_app.png
  modules/ROOT/pages/web_app.adoc
  modules/ROOT/partials/nav.adoc
Labels: documentation

#338 [3.0] [PR 335] Open files in online office suite
  modules/ROOT/images/web_app/office_file_context_menu.png
  modules/ROOT/images/web_app/office_file_in_browser.png
  modules/ROOT/images/web_app/office_file_in_explorer.png
  modules/ROOT/images/web_app/office_file_in_web_app.png
  modules/ROOT/pages/web_app.adoc
  modules/ROOT/partials/nav.adoc
Labels: backport

#339 Fix image width
  modules/ROOT/pages/appendices/troubleshooting.adoc
  modules/ROOT/pages/faq.adoc
  modules/ROOT/pages/installing.adoc
  modules/ROOT/pages/navigating.adoc
  modules/ROOT/pages/vfs.adoc
Labels: documentation

#340 [3.0] [PR 339] Fix image width
  modules/ROOT/pages/appendices/troubleshooting.adoc
  modules/ROOT/pages/faq.adoc
  modules/ROOT/pages/installing.adoc
  modules/ROOT/pages/navigating.adoc
  modules/ROOT/pages/vfs.adoc
Labels: backport

#341 [2.11] [PR 339] Fix image width
  modules/ROOT/pages/appendices/troubleshooting.adoc
  modules/ROOT/pages/faq.adoc
  modules/ROOT/pages/installing.adoc
  modules/ROOT/pages/navigating.adoc
  modules/ROOT/pages/vfs.adoc
Labels: backport

#342 Explain cleanup of Not Synced messages
  modules/ROOT/pages/faq.adoc
Labels: documentation

#343 [3.0] [PR 342] Explain cleanup of Not Synced messages
  modules/ROOT/pages/faq.adoc
Labels: backport

#344 [2.11] [PR 342] Explain cleanup of Not Synced messages
  modules/ROOT/pages/faq.adoc
Labels: backport

#345 [master] [317] [Windows] Clarify requirement for native WinVFS
  modules/ROOT/pages/faq.adoc
  modules/ROOT/pages/installing.adoc
  modules/ROOT/pages/vfs.adoc
Labels: backport

#346 [2.11] [PR 317] [Windows] Clarify requirement for native WinVFS
  modules/ROOT/pages/faq.adoc
  modules/ROOT/pages/installing.adoc
  modules/ROOT/pages/vfs.adoc
Labels: backport

#349 Changes necessary for 3.1
  .drone.star
  site.yml
Labels: deployment

#350 Update the text for creating a new branch
  docs/new-version-branch.md
Labels: deployment

#351 How to fix signature verification errors
  modules/ROOT/pages/installing.adoc
Labels: documentation

#353 [3.0] [PR 351] How to fix signature verification errors
  modules/ROOT/pages/installing.adoc
Labels: backport

#352 [3.1] [PR 351] How to fix signature verification errors
  modules/ROOT/pages/installing.adoc
Labels: backport

#356 update desktop app testing docs for ocis
  modules/ROOT/pages/appendices/guitest.adoc
Labels: documentation

#357 [3.1] [PR 356] update desktop app testing docs for ocis
  modules/ROOT/pages/appendices/guitest.adoc
Labels: backport

#358 [3.0] [PR 356] update desktop app testing docs for ocis
  modules/ROOT/pages/appendices/guitest.adoc
Labels: backport
