Repository owncloud/docs-client-desktop, pull requests merged in 2023-02, with the labels that each got.

#354 Removing a Sync Connection
  modules/ROOT/images/navigating/remove_sync_connection.png
  modules/ROOT/pages/navigating.adoc
Labels: documentation

#360 [3.0] [PR 354] Removing a Sync Connection
  modules/ROOT/images/navigating/remove_sync_connection.png
  modules/ROOT/pages/navigating.adoc
Labels: backport

#359 [3.1] [PR 354] Removing a Sync Connection
  modules/ROOT/images/navigating/remove_sync_connection.png
  modules/ROOT/pages/navigating.adoc
Labels: backport

#364 [3.0] [PR 363] owncloudcmd new WebDAV endpoint
  modules/ROOT/pages/advanced_usage/command_line_client.adoc
Labels: backport

#367 Update the log window image
  modules/ROOT/images/appendices/troubleshooting/log_output_window.png
  modules/ROOT/pages/appendices/troubleshooting.adoc
Labels: documentation

#366 Add crash report info in the troubleshooting documentation
  modules/ROOT/images/appendices/troubleshooting/crash-report-created.png
  modules/ROOT/images/appendices/troubleshooting/crash-report-sent.png
  modules/ROOT/pages/appendices/troubleshooting.adoc
Labels: documentation

#368 [3.1] [PR 367] Update the log window image
  modules/ROOT/images/appendices/troubleshooting/log_output_window.png
  modules/ROOT/pages/appendices/troubleshooting.adoc
Labels: backport

#369 [3.0] [PR 367] Update the log window image
  modules/ROOT/images/appendices/troubleshooting/log_output_window.png
  modules/ROOT/pages/appendices/troubleshooting.adoc
Labels: backport

#370 [3.1] [PR 366] Add crash report info in the troubleshooting documentation
  modules/ROOT/images/appendices/troubleshooting/crash-report-created.png
  modules/ROOT/images/appendices/troubleshooting/crash-report-sent.png
  modules/ROOT/pages/appendices/troubleshooting.adoc
Labels: backport

#371 [3.0] [PR 366] Add crash report info in the troubleshooting documentation
  modules/ROOT/images/appendices/troubleshooting/crash-report-created.png
  modules/ROOT/images/appendices/troubleshooting/crash-report-sent.png
  modules/ROOT/pages/appendices/troubleshooting.adoc
Labels: backport

#374 Changes necessary for 3.2
  .drone.star
  site.yml
Labels: deployment

#376 [3.2] [PR 375] Update AppImage-specific insructions for upcoming 3.2 release
  modules/ROOT/pages/installing.adoc
Labels: backport

#377 Move and update the description attribute to the correct place
  modules/ROOT/pages/advanced_usage/command_line_client.adoc
  modules/ROOT/pages/advanced_usage/configuration_file.adoc
  modules/ROOT/pages/advanced_usage/environment_variables.adoc
  modules/ROOT/pages/advanced_usage/low_disk_space.adoc
  modules/ROOT/pages/appendices/architecture.adoc
  modules/ROOT/pages/appendices/building.adoc
  modules/ROOT/pages/appendices/guitest.adoc
  modules/ROOT/pages/appendices/troubleshooting.adoc
  modules/ROOT/pages/automatic_updater.adoc
  modules/ROOT/pages/conflicts.adoc
  modules/ROOT/pages/faq.adoc
  modules/ROOT/pages/filenames.adoc
  modules/ROOT/pages/installing.adoc
  modules/ROOT/pages/navigating.adoc
  modules/ROOT/pages/vfs.adoc
  modules/ROOT/pages/web_app.adoc
Labels: documentation

#379 [3.1] [PR 377] Move and update the description attribute to the corre…
  modules/ROOT/pages/advanced_usage/command_line_client.adoc
  modules/ROOT/pages/advanced_usage/configuration_file.adoc
  modules/ROOT/pages/advanced_usage/environment_variables.adoc
  modules/ROOT/pages/advanced_usage/low_disk_space.adoc
  modules/ROOT/pages/appendices/architecture.adoc
  modules/ROOT/pages/appendices/building.adoc
  modules/ROOT/pages/appendices/guitest.adoc
  modules/ROOT/pages/appendices/troubleshooting.adoc
  modules/ROOT/pages/automatic_updater.adoc
  modules/ROOT/pages/conflicts.adoc
  modules/ROOT/pages/faq.adoc
  modules/ROOT/pages/filenames.adoc
  modules/ROOT/pages/installing.adoc
  modules/ROOT/pages/navigating.adoc
  modules/ROOT/pages/vfs.adoc
  modules/ROOT/pages/web_app.adoc
Labels: backport

#378 [3.2] [PR 377] Move and update the description attribute to the corre…
  modules/ROOT/pages/advanced_usage/command_line_client.adoc
  modules/ROOT/pages/advanced_usage/configuration_file.adoc
  modules/ROOT/pages/advanced_usage/environment_variables.adoc
  modules/ROOT/pages/advanced_usage/low_disk_space.adoc
  modules/ROOT/pages/appendices/architecture.adoc
  modules/ROOT/pages/appendices/building.adoc
  modules/ROOT/pages/appendices/guitest.adoc
  modules/ROOT/pages/appendices/troubleshooting.adoc
  modules/ROOT/pages/automatic_updater.adoc
  modules/ROOT/pages/conflicts.adoc
  modules/ROOT/pages/faq.adoc
  modules/ROOT/pages/filenames.adoc
  modules/ROOT/pages/installing.adoc
  modules/ROOT/pages/navigating.adoc
  modules/ROOT/pages/vfs.adoc
  modules/ROOT/pages/web_app.adoc
Labels: backport

#381 [master] [PR 380] Ubuntu 21.10 has become end of life
  modules/ROOT/pages/installing.adoc
Labels: backport

#383 [master] [PR 382] Bring back lost OCC_UPDATE_URL
  modules/ROOT/pages/advanced_usage/environment_variables.adoc
Labels: backport

#386 Windows VFS requires files ownership
  modules/ROOT/images/appendices/troubleshooting/advanced_security_settings.png
  modules/ROOT/images/appendices/troubleshooting/folder_properties.png
  modules/ROOT/pages/appendices/troubleshooting.adoc
  modules/ROOT/pages/vfs.adoc
Labels: documentation

#387 [3.2] [PR 386] Windows VFS requires files ownership
  modules/ROOT/images/appendices/troubleshooting/advanced_security_settings.png
  modules/ROOT/images/appendices/troubleshooting/folder_properties.png
  modules/ROOT/pages/appendices/troubleshooting.adoc
  modules/ROOT/pages/vfs.adoc
Labels: backport

#388 [3.1] [PR 386] Windows VFS requires files ownership
  modules/ROOT/images/appendices/troubleshooting/advanced_security_settings.png
  modules/ROOT/images/appendices/troubleshooting/folder_properties.png
  modules/ROOT/pages/appendices/troubleshooting.adoc
  modules/ROOT/pages/vfs.adoc
Labels: backport

#389 Fix typo
  modules/ROOT/pages/appendices/troubleshooting.adoc
Labels: documentation
