Repository owncloud/docs-client-desktop, pull requests merged in 2024-01, with the labels that each got.

#564 [5.2] [PR 563] Update installing.adoc with the latest stable build nu…
  modules/ROOT/pages/installing.adoc
Labels: backport

#567 Antora 3.1 upgrade
  .drone.star
  antora.yml
  docs/new-version-branch.md
  ext-antora/generate-index.js
  ext-asciidoc/ext-antora/generate-index.js
  ext-asciidoc/remote-include-processor.js
  ext-asciidoc/tabs.js
  generator/generate-site.js
  generator/xref-validator.js
  package.json
  site.yml
  yarn.lock
Labels: dependencies, deployment

#569 [5.2] [PR 567] Antora 3.1 upgrade
  .drone.star
  antora.yml
  docs/new-version-branch.md
  ext-antora/generate-index.js
  ext-asciidoc/ext-antora/generate-index.js
  ext-asciidoc/remote-include-processor.js
  ext-asciidoc/tabs.js
  generator/generate-site.js
  generator/xref-validator.js
  package.json
  site.yml
  yarn.lock
Labels: backport

#570 [5.1] [PR 567] Antora 3.1 upgrade
  .drone.star
  antora.yml
  docs/new-version-branch.md
  ext-antora/generate-index.js
  ext-asciidoc/ext-antora/generate-index.js
  ext-asciidoc/remote-include-processor.js
  ext-asciidoc/tabs.js
  generator/generate-site.js
  generator/xref-validator.js
  package.json
  site.yml
  yarn.lock
Labels: backport

#571 Just a small internal link fix
  docs/new-version-branch.md
Labels: documentation

#572 [5.2] [PR 571] Just a small internal link fix
  docs/new-version-branch.md
Labels: backport
