Repository owncloud/docs-client-desktop, pull requests merged in 2024-06, with the labels that each got.

#598 Fix command typo in generate-index.js
  ext-antora/generate-index.js
Labels: bug

#599 [5.2] [PR 598] Fix command typo in generate-index.js
  ext-antora/generate-index.js
Labels: backport

#600 Changes necessary for Desktop 5.3
  .drone.star
Labels: deployment

#602 [5.3] [PR 601] docs: update client version in the installation doc
  modules/ROOT/pages/installing.adoc
Labels: backport
